before:
  hooks:
    # - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - -s -w -X main.Version={{.Version}}
    hooks:
      post: upx -qqq -9 {{ .Path }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    homepage: https://github.com/cpliakas/goreleaser-test
    description: Test creating a Homebrew tap with goreleaser.
    folder: Formula
    license: "MIT"

    tap:
      owner: cpliakas
      name: homebrew-tap

    commit_author:
      name: cpliakas
      email: cpliakas@gmail.com

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/cpliakas/goreleaser-test
    description: Test creating a Homebrew tap with goreleaser.
    maintainer: Chris Pliakas <opensource@chrispliakas.com>
    license: MIT
    vendor: cpliakas
    formats:
    - deb
    - rpm
